-- Flyway migration script to create t_users table for User entity
CREATE SEQUENCE t_users_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE t_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255),
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    email VARCHAR(255),
    password VARCHAR(255),
    phone VARCHAR(255),
    user_status INTEGER
);
